// Polygon meshes for the Dark Mod quarter (textured half-timber houses, workshops, manor, city wall, smooth
// cobbled lanes) and the Yorg race track (smooth asphalt ribbon, kerbs, tyre walls, gantry, grandstand, pit).
// Collision stays on an invisible barrier grid generated by the server; these meshes are what you see.
import * as THREE from 'three'
import { GeoBuilder, surfaceMaterial, loadTex } from './surfmat'
import type { VoxSource } from './dukemap'
// eslint-disable-next-line @typescript-eslint/no-require-imports
const layout = require('../layout')
// eslint-disable-next-line @typescript-eslint/no-require-imports
const darkmod = require('../zones/darkmod')

const TDM = './darkmod/tex'
type Bag = Map<string, GeoBuilder>
const bag = (b: Bag, k: string) => { let g = b.get(k); if (!g) { g = new GeoBuilder(); b.set(k, g) } return g }
const COL: Record<string, [number, number, number]> = {
  stone: [128, 124, 118], stone2: [110, 108, 104], halftimber: [190, 180, 160], halftimber_win: [170, 160, 140], gable: [180, 170, 150], workshop: [140, 80, 60],
  roof_red: [140, 60, 50], roof_brown: [100, 70, 50], roof_old: [90, 85, 80], shingle: [80, 80, 90], cobble: [120, 118, 112], planks: [150, 110, 70],
  asphalt: [70, 70, 74], white: [230, 230, 230], red: [200, 40, 30], black: [30, 30, 30], blue: [40, 70, 180], grey: [170, 170, 170]
}

function box (g: GeoBuilder, x0: number, z0: number, x1: number, z1: number, y0: number, y1: number, us = 0.25, vs = 0.25, top = true) {
  g.wall(x0, z0, x1, z0, y0, y1, 0.82, us, vs); g.wall(x1, z0, x1, z1, y0, y1, 0.68, us, vs)
  g.wall(x1, z1, x0, z1, y0, y1, 0.82, us, vs); g.wall(x0, z1, x0, z0, y0, y1, 0.68, us, vs)
  if (top) { const a = g.v(x0, y1, z0, x0 * us, z0 * us, 1); const b = g.v(x1, y1, z0, x1 * us, z0 * us, 1); const c = g.v(x1, y1, z1, x1 * us, z1 * us, 1); const d = g.v(x0, y1, z1, x0 * us, z1 * us, 1); g.quad(a, d, c, b) }
}
/** wall along x at z with door gaps [[a,b,h]] */
function wallX (g: GeoBuilder, x0: number, x1: number, z: number, y0: number, y1: number, gaps: Array<[number, number, number]>, us = 0.25) {
  let x = x0
  for (const [a, b, h] of gaps) {
    if (a > x) g.wall(x, z, a, z, y0, y1, 0.82, us, us)
    g.wall(a, z, b, z, y0 + h, y1, 0.82, us, us)
    x = b
  }
  if (x < x1) g.wall(x, z, x1, z, y0, y1, 0.82, us, us)
}

function buildDarkMod (rx: number, rz: number, seed: number) {
  const G = layout.ZONE_G; const ox = rx * layout.REGION + 32; const oz = rz * layout.REGION + 32
  const b: Bag = new Map(); const ctx = { seed, rx, rz }
  const roofTex = (c: any) => ['roof_brown', 'roof_old', 'roof_red', 'shingle'][['dark_oak_stairs', 'spruce_stairs', 'brick_stairs', 'stone_brick_stairs'].indexOf(c.roof[0])] ?? 'roof_red'
  for (let ci = 0; ci < 6; ci++) {
    for (let cj = 0; cj < 6; cj++) {
      const c = darkmod.cellInfo(ci, cj, ctx)
      if (!c.ok) continue
      const x0 = ox + c.u0; const z0 = oz + c.v0; const x1 = x0 + c.w; const z1 = z0 + c.d
      if (c.type === 'house') {
        const dx = x0 + (c.w >> 1)
        const lo = bag(b, 'stone'); lo.cur = COL.stone
        wallX(lo, x0, x1, z0, G + 1, G + 5, [[dx, dx + 1, 2]])
        lo.wall(x1, z0, x1, z1, G + 1, G + 5, 0.68, 0.25, 0.25); lo.wall(x1, z1, x0, z1, G + 1, G + 5, 0.82, 0.25, 0.25); lo.wall(x0, z1, x0, z0, G + 1, G + 5, 0.68, 0.25, 0.25)
        const up = bag(b, 'halftimber_win'); up.cur = COL.halftimber_win
        box(up, x0, z0, x1, z1, G + 5, G + 9, 0.25, 0.25, false)
        // gable ends + roof planes
        const ridge = G + 9 + (c.d + 1) / 2; const zm = (z0 + z1) / 2
        const gb = bag(b, 'gable'); gb.cur = COL.gable
        for (const x of [x0, x1]) { const p = gb.v(x, G + 9, z0, z0 * 0.25, 0, 0.75); const q = gb.v(x, G + 9, z1, z1 * 0.25, 0, 0.75); const r = gb.v(x, ridge, zm, zm * 0.25, (ridge - G - 9) * 0.25, 0.75); gb.tri(p, q, r) }
        const rf = bag(b, roofTex(c)); rf.cur = COL[roofTex(c)]
        const L = Math.hypot(zm - (z0 - 1), ridge - (G + 8.5))
        for (const [za, sh] of [[z0 - 1, 0.95], [z1 + 1, 0.8]] as Array<[number, number]>) {
          const p = rf.v(x0 - 0.6, G + 8.5, za, 0, 0, sh); const q = rf.v(x1 + 0.6, G + 8.5, za, (c.w + 1.2) / 3, 0, sh)
          const r = rf.v(x1 + 0.6, ridge + 0.15, zm, (c.w + 1.2) / 3, L / 3, sh); const s = rf.v(x0 - 0.6, ridge + 0.15, zm, 0, L / 3, sh)
          za < zm ? rf.quad(p, q, r, s) : rf.quad(q, p, s, r)
        }
        const fl = bag(b, 'planks'); fl.cur = COL.planks
        box(fl, x0 + 0.05, z0 + 0.05, x1 - 0.05, z1 - 0.05, G + 1, G + 1.02, 0.5, 0.5)
        const ch = bag(b, 'stone2'); ch.cur = COL.stone2
        box(ch, x0 + c.w - 2, z0 + 1, x0 + c.w - 1, z0 + 2, G + 1, G + 15)
      } else if (c.type === 'workshop') {
        const g = bag(b, 'workshop'); g.cur = COL.workshop
        const dx = x0 + (c.w >> 1)
        wallX(g, x0, x1, z0, G + 1, G + 8, [[dx - 1, dx + 2, 3]])
        g.wall(x1, z0, x1, z1, G + 1, G + 8, 0.68, 0.25, 0.25); g.wall(x1, z1, x0, z1, G + 1, G + 8, 0.82, 0.25, 0.25); g.wall(x0, z1, x0, z0, G + 1, G + 8, 0.68, 0.25, 0.25)
        const r = bag(b, 'shingle'); r.cur = COL.shingle
        box(r, x0 - 0.3, z0 - 0.3, x1 + 0.3, z1 + 0.3, G + 8, G + 8.3, 0.3, 0.3)
        box(bag(b, 'stone2'), x0 + 2, z0 + c.d - 3, x0 + 3, z0 + c.d - 2, G + 8, G + 17)
      } else {
        const g = bag(b, 'stone'); g.cur = COL.stone
        wallX(g, x0, x1, z0, G + 1, G + 11, [[x0 + 7, x0 + 9, 3]])
        g.wall(x1, z0, x1, z1, G + 1, G + 11, 0.68, 0.25, 0.25); g.wall(x1, z1, x0, z1, G + 1, G + 11, 0.82, 0.25, 0.25); g.wall(x0, z1, x0, z0, G + 1, G + 11, 0.68, 0.25, 0.25)
        const t = bag(b, 'stone2'); t.cur = COL.stone2
        for (const [a, c2] of [[x0, z0], [x1 - 3, z0], [x0, z1 - 3], [x1 - 3, z1 - 3]]) {
          box(t, a - 0.2, c2 - 0.2, a + 3.2, c2 + 3.2, G + 1, G + 15)
          const rf = bag(b, 'roof_old'); rf.cur = COL.roof_old
          const tip = rf.v(a + 1.5, G + 19, c2 + 1.5, 0.5, 1, 1)
          const cs = [[a - 0.5, c2 - 0.5], [a + 3.5, c2 - 0.5], [a + 3.5, c2 + 3.5], [a - 0.5, c2 + 3.5]]
          for (let k = 0; k < 4; k++) { const p = cs[k]; const q = cs[(k + 1) % 4]; rf.tri(rf.v(p[0], G + 15, p[1], 0, 0, 0.85), rf.v(q[0], G + 15, q[1], 1, 0, 0.85), tip) }
        }
        const rf = bag(b, 'roof_old'); rf.cur = COL.roof_old
        box(rf, x0 + 0.2, z0 + 0.2, x1 - 0.2, z1 - 0.2, G + 11, G + 11.3, 0.3, 0.3)
      }
    }
  }
  // smooth cobbled lanes + plaza + fountain rim
  const cob = bag(b, 'cobble'); cob.cur = COL.cobble
  const lane = (f: (t: number) => [number, number]) => {
    let prev: number[] | null = null
    for (let t = -1; t <= 129; t += 1) {
      const [u, v] = f(t); const [u2, v2] = f(t + 0.01)
      const dx = u2 - u; const dz = v2 - v; const l = Math.hypot(dx, dz); const nx = -dz / l * 3.2; const nz = dx / l * 3.2
      const y = G + 1.04
      const a = cob.v(ox + u + nx, y, oz + v + nz, t / 3, 0, 1); const c = cob.v(ox + u - nx, y, oz + v - nz, t / 3, 6.4 / 3, 1)
      if (prev) cob.quad(prev[0], prev[1], c, a)
      prev = [a, c]
    }
  }
  lane(t => [t, 64 + 5 * Math.sin(t / 13)]); lane(t => [64 + 5 * Math.sin(t / 11), t])
  const N = 40
  for (let k = 0; k < N; k++) {
    const a0 = k / N * Math.PI * 2; const a1 = (k + 1) / N * Math.PI * 2
    const pt = (a: number, r: number, y: number) => cob.v(ox + 64 + Math.cos(a) * r, y, oz + 64 + Math.sin(a) * r, Math.cos(a) * r / 3, Math.sin(a) * r / 3, 1)
    cob.quad(pt(a0, 3.5, G + 1.05), pt(a1, 3.5, G + 1.05), pt(a1, 9.3, G + 1.05), pt(a0, 9.3, G + 1.05))
    const st = bag(b, 'stone'); st.cur = COL.stone
    st.wall(ox + 64 + Math.cos(a0) * 3.5, oz + 64 + Math.sin(a0) * 3.5, ox + 64 + Math.cos(a1) * 3.5, oz + 64 + Math.sin(a1) * 3.5, G + 0.9, G + 2, 0.8)
    st.wall(ox + 64 + Math.cos(a1) * 2.5, oz + 64 + Math.sin(a1) * 2.5, ox + 64 + Math.cos(a0) * 2.5, oz + 64 + Math.sin(a0) * 2.5, G + 0.9, G + 2, 0.7)
  }
  box(bag(b, 'stone'), ox + 63.6, oz + 63.6, ox + 64.4, oz + 64.4, G + 1, G + 3.5)
  // city wall ring with gates where the lanes cross
  const wall = bag(b, 'stone2'); wall.cur = COL.stone2
  const gate = (u: number, v: number) => Math.abs(v - 64 - 5 * Math.sin(u / 13)) <= 3.5 || Math.abs(u - 64 - 5 * Math.sin(v / 11)) <= 3.5
  const sides: Array<(s: number) => [number, number]> = [s => [s, 1.5], s => [s, 126.5], s => [1.5, s], s => [126.5, s]]
  for (const f of sides) {
    let start = 0
    for (let s = 0; s <= 128; s++) {
      const [u, v] = f(Math.min(s, 127)); const g = s === 128 || gate(u, v)
      if (g) {
        if (s > start) {
          const [ua, va] = f(start); const [ub, vb] = f(s)
          const hor = va === vb
          box(wall, ox + (hor ? ua : ua - 1.5), oz + (hor ? va - 1.5 : va), ox + (hor ? ub : ua + 1.5), oz + (hor ? va + 1.5 : vb), G + 1, G + 8, 0.25, 0.25)
        }
        if (s < 128) { const [u2, v2] = f(s); const hor = v2 === f(0)[1]; box(wall, ox + (hor ? u2 : u2 - 1.5), oz + (hor ? v2 - 1.5 : v2), ox + (hor ? u2 + 1 : u2 + 1.5), oz + (hor ? v2 + 1.5 : v2 + 1), G + 6, G + 8) }
        start = s + 1
      }
    }
  }
  const group = new THREE.Group(); group.name = `tdm-${rx},${rz}`
  const sources: VoxSource[] = []
  for (const [k, g] of b) {
    const mesh = new THREE.Mesh(g.build(), surfaceMaterial({ map: loadTex(`${TDM}/${k}.jpg`), side: THREE.DoubleSide }))
    group.add(mesh); sources.push({ pos: g.pos, idx: g.idx, tc: g.tc })
  }
  return { group, sources }
}

function buildYorg (rx: number, rz: number) {
  const G = layout.ZONE_G; const ox = rx * layout.REGION + 32; const oz = rz * layout.REGION + 32
  const cx = ox + 63.5 + 0.5; const cz = oz + 63.5 + 0.5
  const A = 22; const R = 34; const HW = 6
  const L = 4 * A + 2 * Math.PI * R
  // centre line point + outward normal for arc length s (s=0 at x=0 on the +z straight, going -x like the block layout)
  const at = (s: number): [number, number, number, number] => {
    s = ((s % L) + L) % L
    if (s < A) return [-s, R, 0, 1]
    s -= A
    if (s < Math.PI * R) { const a = Math.PI / 2 + s / R; return [-A + Math.cos(a) * R, Math.sin(a) * R, Math.cos(a), Math.sin(a)] }
    s -= Math.PI * R
    if (s < 2 * A) return [-A + s, -R, 0, -1]
    s -= 2 * A
    if (s < Math.PI * R) { const a = -Math.PI / 2 + s / R; return [A + Math.cos(a) * R, Math.sin(a) * R, Math.cos(a), Math.sin(a)] }
    s -= Math.PI * R
    return [A - s, R, 0, 1]
  }
  const road = new GeoBuilder(); road.cur = COL.asphalt
  const kerb = new GeoBuilder()
  const y = G + 1.03
  const STEP = 1
  for (let s = 0; s < L; s += STEP) {
    const p = at(s); const q = at(s + STEP)
    const P = (pt: number[], o: number, yy = y) => [cx + pt[0] + pt[2] * o, yy, cz + pt[1] + pt[3] * o]
    const strip = (g: GeoBuilder, o0: number, o1: number, c: number, uv0 = 0, yy = y) => {
      const a = P(p, o0, yy); const b2 = P(p, o1, yy); const c2 = P(q, o1, yy); const d = P(q, o0, yy)
      const i0 = g.v(a[0], a[1], a[2], uv0 + s / 4, o0 / 4, c); const i1 = g.v(b2[0], b2[1], b2[2], uv0 + s / 4, o1 / 4, c)
      const i2 = g.v(c2[0], c2[1], c2[2], uv0 + (s + STEP) / 4, o1 / 4, c); const i3 = g.v(d[0], d[1], d[2], uv0 + (s + STEP) / 4, o0 / 4, c)
      g.quad(i0, i3, i2, i1)
    }
    strip(road, -HW + 1, HW - 1, 0.32)
    const red = Math.floor(s / 2) % 2 === 0
    kerb.cur = kerb.tint = red ? COL.red : COL.white
    strip(kerb, -HW, -HW + 1, 1, 0, y + 0.02); strip(kerb, HW - 1, HW, 1, 0, y + 0.02)
    // tyre wall (outside, gap at the pit entry)
    const isPitGap = Math.abs(p[0]) < 3 && p[1] < 0
    if (!isPitGap) { const tw = P(p, HW + 1); const tw2 = P(q, HW + 1); tyre.push([tw[0], tw[2], tw2[0], tw2[2], Math.abs(p[0]) > A ? 2 : 1]) }
  }
  // start/finish checker at x = 0
  const chk = new GeoBuilder()
  for (let i = 0; i < 12; i++) {
    for (let j = 0; j < 2; j++) {
      const c = (i + j) % 2 ? 0.08 : 1
      const x0 = cx - 1 + j; const z0 = cz + R - HW + i
      chk.quad(chk.v(x0, y + 0.03, z0, 0, 0, c), chk.v(x0, y + 0.03, z0 + 1, 0, 0, c), chk.v(x0 + 1, y + 0.03, z0 + 1, 0, 0, c), chk.v(x0 + 1, y + 0.03, z0, 0, 0, c))
    }
  }
  // gantry
  const dark = new GeoBuilder(); dark.cur = COL.black; dark.tint = [70, 70, 70]
  box(dark, cx - 0.5, cz + R - HW - 1.6, cx + 0.5, cz + R - HW - 0.6, G + 1, G + 8); box(dark, cx - 0.5, cz + R + HW + 0.6, cx + 0.5, cz + R + HW + 1.6, G + 1, G + 8)
  box(dark, cx - 0.6, cz + R - HW - 1.6, cx + 0.6, cz + R + HW + 1.6, G + 7, G + 8)
  for (const t of tyre) { dark.wall(t[0], t[1], t[2], t[3], G + 1, G + 1 + t[4], 0.35, 1, 1); }
  // grandstand: stepped seats
  const stand = new GeoBuilder()
  for (let k = 1; k <= 7; k++) {
    const z0 = cz + R + HW + 2 + (k - 1) * 1.5; stand.cur = stand.tint = k % 2 ? COL.red : COL.blue
    box(stand, cx - 18, z0, cx + 18, z0 + 1.5, G + 1, G + 1 + k, 0.5, 0.5)
  }
  stand.cur = stand.tint = COL.white
  box(stand, cx - 18, cz + R + HW + 12, cx + 18, cz + R + HW + 12.4, G + 1, G + 10)
  // pit garage
  const pit = new GeoBuilder(); pit.cur = COL.grey
  wallX(pit, cx - 12, cx + 12, cz - 6, G + 1, G + 5, [[cx - 10, cx + 10, 3]], 0.5)
  pit.wall(cx + 12, cz - 6, cx + 12, cz + 6, G + 1, G + 5, 0.7, 0.5, 0.5); pit.wall(cx + 12, cz + 6, cx - 12, cz + 6, G + 1, G + 5, 0.85, 0.5, 0.5); pit.wall(cx - 12, cz + 6, cx - 12, cz - 6, G + 1, G + 5, 0.7, 0.5, 0.5)
  box(pit, cx - 12.3, cz - 6.3, cx + 12.3, cz + 6.3, G + 5, G + 5.4, 0.5, 0.5)
  box(pit, cx - 12, cz - 6, cx + 12, cz + 6, G + 1, G + 1.02, 0.5, 0.5)
  const group = new THREE.Group(); group.name = `yorg-${rx},${rz}`
  const sources: VoxSource[] = []
  for (const [g, tex] of [[road, `${TDM}/stone2.jpg`], [kerb, ''], [chk, ''], [dark, ''], [stand, ''], [pit, `${TDM}/stone.jpg`]] as Array<[GeoBuilder, string]>) {
    if (!g.n) continue
    const mesh = new THREE.Mesh(g.build(), surfaceMaterial({ map: tex ? loadTex(tex) : null, side: THREE.DoubleSide }))
    group.add(mesh); sources.push({ pos: g.pos, idx: g.idx, tc: g.tc })
  }
  return { group, sources }
}
const tyre: number[][] = []

export function buildZoneMeshes (px: number, pz: number, seed: number, built: Set<string>) {
  const out: Array<{ key: string, group: THREE.Group, sources: VoxSource[] }> = []
  const rx0 = Math.floor(px / layout.REGION); const rz0 = Math.floor(pz / layout.REGION)
  for (let dx = -1; dx <= 1; dx++) {
    for (let dz = -1; dz <= 1; dz++) {
      const rx = rx0 + dx; const rz = rz0 + dz; const key = `${rx},${rz}`
      if (built.has(key)) continue
      const t = layout.zoneType(rx, rz, seed)
      if (t === 'darkmod') { built.add(key); out.push({ key, ...buildDarkMod(rx, rz, seed) }) }
      if (t === 'yorg') { built.add(key); tyre.length = 0; out.push({ key, ...buildYorg(rx, rz) }) }
    }
  }
  return out
}
